### PR TITLE
Fixed #365. software i2c doesn't work

### LINKED ISSUE #365: SoftwareI2C doesn't work
Software I2C doesn't work when move from native to managed.

Corrected OpenPins to get Sda and Scl affected but there probably more than one issues.

Move to next important thing.

### PR DESCRIPTION
**Pull request by Palomino34**

### CODE REVIEW

File: Targets/STM32F4xx/STM32F4_GPIO.cpp [hunk 1]
```diff
@@ -53,6 +53,7 @@ static bool pinReserved[TOTAL_GPIO_PINS];
 static int64_t gpioDebounceInTicks[TOTAL_GPIO_PINS];
 static GpioInterruptState gpioInterruptState[TOTAL_GPIO_INTERRUPT_PINS];
 static TinyCLR_Gpio_PinDriveMode pinDriveMode[TOTAL_GPIO_PINS];
+static TinyCLR_Gpio_PinValue pinWasOutputValue[TOTAL_GPIO_PINS];
```
Comment (Arke64) [inline Targets/STM32F4xx/STM32F4_GPIO.cpp]: Rename to `previousOutputValue`

**Comment by Palomino34** [comment]
This also fixed #293. Verified software SPI on G80 and G400.
